pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/seuusuario/seurepositorio-api.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npx cypress run'
            }
        }
        stage('Archive Results') {
            steps {
                junit 'cypress/results/*.xml'
                archiveArtifacts artifacts: 'cypress/screenshots/**', allowEmptyArchive: true
                archiveArtifacts artifacts: 'cypress/videos/**', allowEmptyArchive: true
            }
        }
    }
}