pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/seuusuario/seurepositorio-web.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }
        stage('Archive Reports') {
            steps {
                junit 'reports/**/*.xml'
            }
        }
    }
}